version: "3.9"
services:
  user_backend:
    container_name: users_ms
    build: .
    volumes:
      - /app/vendor
      - .:/app
    command: "php artisan serve --host=0.0.0.0"
    depends_on:
      - user_db
    networks:
      - users 

  user_db:
    image: amd64/mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - users 

networks:
    users:
        name: users 